# Generated by Django 3.0.6 on 2020-05-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temphum', '0002_auto_20200513_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='temphum',
            name='long',
            field=models.CharField(default=2, max_length=20, verbose_name='Longitud'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='temphum',
            name='latitud',
            field=models.IntegerField(verbose_name='Latitud'),
        ),
    ]
