# Generated by Django 3.0.6 on 2020-05-13 22:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('temphum', '0003_auto_20200513_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temphum',
            name='long',
        ),
        migrations.AddField(
            model_name='temphum',
            name='longitud',
            field=models.IntegerField(default=django.utils.timezone.now, verbose_name='Longitud'),
            preserve_default=False,
        ),
    ]
