# Generated by Django 3.0.6 on 2020-05-13 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temphum', '0004_auto_20200513_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temphum',
            name='longitud',
        ),
    ]
